#include "upgrade.h"
#include "shared.h"
#include "pilot.h"
#include <list>


static SModifier SNone = [](const Pilot&) { return 0;};
static AModifier ANone = [](const Pilot&) { return Act::None;};
static UModifier UNone = [](const Pilot&) { return std::vector<Upg>(); };

#define S(x)  [](Pilot p) { return x;}

#define cTIX1 [](Pilot p) {for(Upgrade u : p.GetAppliedUpgrades()){ if(u.GetType()==Upg::System){ if(u.GetCost()<=4){return 0-u.GetCost();}else{return -4;} }} return 0;}

#define aBOSL [](Pilot p) { return Act::SLAM;}
#define aENUP [](Pilot p) { return Act::Boost;}
#define aMFAL [](Pilot p) { return Act::Evade;}
#define aMHUN [](Pilot p) { return Act::BarrelRoll;}
#define aTCOM [](Pilot p) { return Act::TargetLock;}
#define aVECT [](Pilot p) { return Act::BarrelRoll;}

#define uANDR [](Pilot p) { return std::vector<Upg>{Upg::Bomb, Upg::Bomb};}
#define uAWTP [](Pilot p) { return std::vector<Upg>{Upg::Elite};}
#define uBWE2 [](Pilot p) { return std::vector<Upg>{Upg::Crew};}
#define uR2D6 [](Pilot p) { return std::vector<Upg>{Upg::Elite};}
#define uRGTI [](Pilot p) { return std::vector<Upg>{Upg::Modification};}
#define uSABW [](Pilot p) { return std::vector<Upg>{Upg::Bomb};}
#define uaTIS [](Pilot p) { return std::vector<Upg>{Upg::Torpedo, Upg::Torpedo, Upg::Missile, Upg::Missile, Upg::Bomb};}
#define urTIS [](Pilot p) { return std::vector<Upg>{Upg::Crew, Upg::Crew};}
#define uSCOM [](Pilot p) { return std::vector<Upg>{Upg::Illicit, Upg::Modification};}
#define uTIX1 [](Pilot p) { return std::vector<Upg>{Upg::System};}
#define uTIX7 [](Pilot p) { return std::vector<Upg>{Upg::Cannon,Upg::Missile};}
#define uVIRA [](Pilot p) { return std::vector<Upg>{Upg::System,Upg::Illicit};}
#define uSAMP [](Pilot p) { return std::vector<Upg>{Upg::Crew,Upg::Illicit};}

std::list<Upgrade> Upgrade::upgrades = {
  // Name                            ShortName           XwsName                      Type                    Slots                    Co  uni    lim      sk     at     ag     hu     sh     co     +act   -act   +upg   -upg
  { "Determination",                "Determination",    "determination",              Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Marksmanship",                 "Marksmanship",     "marksmanship",               Upg::Elite,             {Upg::Elite},             3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Expert Handling",              "Expert Hand",      "experthandling",             Upg::Elite,             {Upg::Elite},             2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "SwarmTactics",                 "Sewarm Tact",      "swarmtactics",               Upg::Elite,             {Upg::Elite},             2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Squad Leader",                 "Squad Leader",     "squadleader",                Upg::Elite,             {Upg::Elite},             2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Draw Their Fire",              "Draw Their Fire",  "drawtheirfire",              Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Elusiveness",                  "Elusiveness",      "elusiveness",                Upg::Elite,             {Upg::Elite},             2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Veteran Instincts",            "VI",               "veteraninstincts",           Upg::Elite,             {Upg::Elite},             1, false, false, {  S(2), SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Expose",                       "Expose",           "expose",                     Upg::Elite,             {Upg::Elite},             4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Deadeye",                      "Deadeye",          "deadeye",                    Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Push the Limit",               "PTL",              "pushthelimit",               Upg::Elite,             {Upg::Elite},             3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Daredevil",                    "Daredevil",        "daredevil",                  Upg::Elite,             {Upg::Elite},             3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Adrenaline Rush",              "Adrenaline Rsh",   "adrenalinerush",             Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Opportunist",                  "Opporunist",       "opportunist",                Upg::Elite,             {Upg::Elite},             4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Decoy",                        "Decoy",            "decoy",                      Upg::Elite,             {Upg::Elite},             2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Wingman",                      "Wingman",          "wingman",                    Upg::Elite,             {Upg::Elite},             2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Outmaneuver",                  "Outmaneuver",      "outmaneuver",                Upg::Elite,             {Upg::Elite},             3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Predator",                     "Predator",         "predator",                   Upg::Elite,             {Upg::Elite},             3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Lone Wolf",                    "Lone Wolf",        "lonewolf",                   Upg::Elite,             {Upg::Elite},             2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Stay on Target",               "Stay on Trgt",     "stayontarget",               Upg::Elite,             {Upg::Elite},             2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Intimidation",                 "Intimidation",     "intimidation",               Upg::Elite,             {Upg::Elite},             2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Ruthlessness",                 "Ruthlessness",     "ruthlessness",               Upg::Elite,             {Upg::Elite},             3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Bodyguard",                    "Bodyguard",        "bodyguard",                  Upg::Elite,             {Upg::Elite},             2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Calculation",                  "Calculation",      "calculation",                Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Crack Shot",                   "Crack Shot",       "crackshot",                  Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Lightning Reflexes",           "Lightning Rf",     "lightningreflexes",          Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Wired",                        "Wired",            "wired",                      Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Cool Hand",                    "Cool Hand",        "coolhand",                   Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Juke",                         "Juke",             "juke",                       Upg::Elite,             {Upg::Elite},             2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Adaptability",                 "Adaptability",     "adaptability",               Upg::Elite,             {Upg::Elite},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Rage",                         "Rage",             "rage",                       Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Attanni Mindlink",             "Attani Mindlink",  "attannimindlink",            Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Fearlessness",                 "Fearlessness",     "fearlessness",               Upg::Elite,             {Upg::Elite},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Snap Shot",                    "Snap Shot",        "snapshot",                   Upg::Elite,             {Upg::Elite},             2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Trick Shot",                   "Trick Shot",       "trickshot",                  Upg::Elite,             {Upg::Elite},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Expertise",                    "Expertise",        "expertise",                  Upg::Elite,             {Upg::Elite},             4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Swarm Leader",                 "Swarm Leader",     "swarmleader",                Upg::Elite,             {Upg::Elite},             3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "A Score to Settle",            "Score to Settle",  "ascoretosettle",             Upg::Elite,             {Upg::Elite},             0, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },

  { "R2-D2",                        "R2-D2",            "r2d2",                       Upg::Astromech,         {Upg::Astromech},         4, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R2-F2",                        "R2-F2",            "r2f2",                       Upg::Astromech,         {Upg::Astromech},         4, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R5 Astromech",                 "R5",               "r5astromech",                Upg::Astromech,         {Upg::Astromech},         1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R5-K6",                        "R5-K6",            "r5k6",                       Upg::Astromech,         {Upg::Astromech},         1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R2 Astromech",                 "R2",               "r2astromech",                Upg::Astromech,         {Upg::Astromech},         1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R5-D8",                        "R5-D8",            "r5d8",                       Upg::Astromech,         {Upg::Astromech},         3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R2-D6",                        "R2-D6",            "r2d6",                       Upg::Astromech,         {Upg::Astromech},         1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, uR2D6, UNone }, {} },
  { "R3-A2",                        "R3-A4",            "r3a2",                       Upg::Astromech,         {Upg::Astromech},         2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R4-D6",                        "R4-D6",            "r4d6",                       Upg::Astromech,         {Upg::Astromech},         1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R5-P9",                        "R5-P9",            "r5p9",                       Upg::Astromech,         {Upg::Astromech},         3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R7 Astromech",                 "R7",               "r7astromech",                Upg::Astromech,         {Upg::Astromech},         2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R7-T1",                        "R7-T1",            "r7t1",                       Upg::Astromech,         {Upg::Astromech},         3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "BB-8",                         "BB-8",             "bb8",                        Upg::Astromech,         {Upg::Astromech},         2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R5-X3",                        "R5-X3",            "r5x3",                       Upg::Astromech,         {Upg::Astromech},         1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Targeting Astromech",          "Targeting Ast",    "targetingastromech",         Upg::Astromech,         {Upg::Astromech},         2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R3 Astromech",                 "R3",               "r3astromech",                Upg::Astromech,         {Upg::Astromech},         2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "M9-G8",                        "M9-G8",            "m9g8",                       Upg::Astromech,         {Upg::Astromech},         3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  
  { "Proton Torpedoes",             "Proton Torp",      "protontorpedoes",            Upg::Torpedo,           {Upg::Torpedo},           4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Adv. Proton Torpedoes",        "Adv. Proton",      "advprotontorpedoes",         Upg::Torpedo,           {Upg::Torpedo},           6, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Flechette Torpedoes",          "Flechette",        "flechettetorpedoes",         Upg::Torpedo,           {Upg::Torpedo},           2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Ion Torpedoes",                "Ion",              "iontorpedoes",               Upg::Torpedo,           {Upg::Torpedo},           5, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Bomb Loadout",                 "Bomb Loadout",     "bombloadout",                Upg::Torpedo,           {Upg::Torpedo},           0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Extra Munitions",              "Extra Mun",        "extramunitions",             Upg::Torpedo,           {Upg::Torpedo},           2, false, true,  { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Plasma Torpedoes",             "Plasma",           "plasmatorpedoes",            Upg::Torpedo,           {Upg::Torpedo},           3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Seismic Torpedo",              "Seismic",          "seismictorpedo",             Upg::Torpedo,           {Upg::Torpedo},           2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },

  { "Ion Cannon Turret",            "Ion Can Tur",      "ioncannonturret",            Upg::Turret,            {Upg::Turret},            5, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Blaster Turret",               "Blaster Turret",   "blasterturret",              Upg::Turret,            {Upg::Turret},            4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Autoblaster Turret",           "Autoblaster",      "autoblasterturret",          Upg::Turret,            {Upg::Turret},            2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Twin Laser Turret",            "TLT",              "twinlaserturret",            Upg::Turret,            {Upg::Turret},            6, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Dorsal Turret",                "Dorsal Turret",    "dorsalturret",               Upg::Turret,            {Upg::Turret},            3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },

  { "Cluster Missiles",             "Cluster Msls",     "clustermissiles",            Upg::Missile,           {Upg::Missile},           4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Concussion Missiles",          "Concussion Msls",  "concussionmissiles",         Upg::Missile,           {Upg::Missile},           4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Assault Missiles",             "Assault Msls",     "assaultmissiles",            Upg::Missile,           {Upg::Missile},           5, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Homing Missiles",              "Homing",           "homingmissiles",             Upg::Missile,           {Upg::Missile},           5, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Ion Pulse Missile",            "Ion Pulse",        "ionpulsemissile",            Upg::Missile,           {Upg::Missile},           3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Chardaan Refit",               "Chardaan Rft",     "chardaanrefit",              Upg::Missile,           {Upg::Missile},          -2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Proton Rockets",               "Proton Rockets",   "protonrockets",              Upg::Missile,           {Upg::Missile},           3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Adv Homing Missile",           "Adv Homing",       "advhomingmissiles",          Upg::Missile,           {Upg::Missile},           3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "XX-23 S-Thread Tracers",       "XX23 Tracers",     "xx23sthreadtracers",         Upg::Missile,           {Upg::Missile},           1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },

  { "Chewbacca",                    "Chewbacca",        "chewbacca",                  Upg::Crew,              {Upg::Crew},              4, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Luke Skywalker",               "Luke Skywalker",   "lukeskywalker",              Upg::Crew,              {Upg::Crew},              7, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Nien Nunb",                    "Nien Nunb",        "niennunb",                   Upg::Crew,              {Upg::Crew},              1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Weapons Engineer",             "Weapons Eng",      "weaponsengineer",            Upg::Crew,              {Upg::Crew},              3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Gunner",                       "Gunner",           "gunner",                     Upg::Crew,              {Upg::Crew},              5, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Mercenary Copilot",            "Merc Copilot",     "mercenarycopilot",           Upg::Crew,              {Upg::Crew},              2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Intelligence Agent",           "Intel Agent",      "intelligenceagent",          Upg::Crew,              {Upg::Crew},              1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Recon Specialist",             "Recon Spec",       "reconspecialist",            Upg::Crew,              {Upg::Crew},              3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Saboteur",                     "Saboteur",         "saboteur",                   Upg::Crew,              {Upg::Crew},              2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Darth Vader",                  "Vader",            "darthvader",                 Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Flight Instructor",            "Flight Inst",      "flightinstructor",           Upg::Crew,              {Upg::Crew},              4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Navigator",                    "Navigator",        "navigator",                  Upg::Crew,              {Upg::Crew},              3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Rebel Captive",                "Rebel Captive",    "rebelcaptive",               Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "C-3PO",                        "C-3PO",            "c3po",                       Upg::Crew,              {Upg::Crew},              3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Han Solo",                     "Han Solo",         "hansolo",                    Upg::Crew,              {Upg::Crew},              2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Leia Organa",                  "Leia Organa",      "leiaorgana",                 Upg::Crew,              {Upg::Crew},              4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R2-D2",                        "R2-D2",            "r2d2",                       Upg::Crew,              {Upg::Crew},              4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Tactician",                    "Tactician",        "tactician",                  Upg::Crew,              {Upg::Crew},              2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Jan Ors",                      "Jan Ors",          "janors",                     Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Kyle Katarn",                  "Kyle Katarn",      "kylekatarn",                 Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "\"Leebo\"",                    "Leebo",            "leebo",                      Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Dash Rendar",                  "Dash",             "dashrendar",                 Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Lando Calrissian",             "Lando",            "landocalrissian",            Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Fleet Officer",                "Fleet Officer",    "fleetofficer",               Upg::Crew,              {Upg::Crew},              3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Mara Jade",                    "Mara Jade",        "marajade",                   Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Moff Jerjerrod",               "Moff Jerjerrod",   "moffjerjerrod",              Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Ysanne Isard",                 "Ysanne Isard",     "ysanneisard",                Upg::Crew,              {Upg::Crew},              4, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Greedo",                       "Greedo",           "greedo",                     Upg::Crew,              {Upg::Crew},              1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "K4 Security Droid",            "K4",               "k4securitydroid",            Upg::Crew,              {Upg::Crew},              3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Outlaw Tech",                  "Outlaw Tech",      "outlawtech",                 Upg::Crew,              {Upg::Crew},              2, false, true,  { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Emperor Palpatine",            "Palp",             "emperorpalpatine",           Upg::Crew,              {Upg::Crew,Upg::Crew},    8, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Bossk",                        "Bossk",            "bossk",                      Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Bombardier",                   "Bombardier",       "bombardier",                 Upg::Crew,              {Upg::Crew},              1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Agent Kallus",                 "Agent Kallus",     "agentkallus",                Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Rear Admiral Chiraneau",       "RADM Chiraneau",   "rearadmiralchiraneau",       Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Construction Droid",           "Const Droid",      "constructiondroid",          Upg::Crew,              {Upg::Crew},              3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "\"Chopper\"",                  "Chopper",          "chopper",                    Upg::Crew,              {Upg::Crew},              0, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "\"Zeb\" Orrelios",             "Zeb",              "zeborrelios",                Upg::Crew,              {Upg::Crew},              1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Ezra Bridger",                 "Ezra",             "ezrabridger",                Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Hera Syndulla",                "Hera",             "herasyndulla",               Upg::Crew,              {Upg::Crew},              1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Kanan Jarrus",                 "Kanan",            "kananjarrus",                Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Sabine Wren",                  "Sabine",           "sabinewren",                 Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, uSABW, UNone }, {} },
  { "4-LOM",                        "4-LOM",            "4lom",                       Upg::Crew,              {Upg::Crew},              1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Zuckuss",                      "Zuckuss",          "zuckuss",                    Upg::Crew,              {Upg::Crew},              1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Gonk",                         "Gonk",             "gonk",                       Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Boba Fett",                    "Boba Fett",        "bobafett",                   Upg::Crew,              {Upg::Crew},              1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Dengar",                       "Dengar",           "dengar",                     Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Systems Officer",              "Sys Officer",      "systemsofficer",             Upg::Crew,              {Upg::Crew},              2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Tail Gunner",                  "Tail Gunner",      "tailgunner",                 Upg::Crew,              {Upg::Crew},              2, false, true,  { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Latts Razzi",                  "Latts Razzi",      "lattsrazzi",                 Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Ketsu Onyo",                   "Ketsu Onyo",       "ketsuonyo",                  Upg::Crew,              {Upg::Crew},              1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "IG-88D",                       "IG-88D",           "ig88d",                      Upg::Crew,              {Upg::Crew},              1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Finn",                         "Finn",             "finn",                       Upg::Crew,              {Upg::Crew},              5, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Rey",                          "Rey",              "rey",                        Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Hotshot Copilot",              "Hotshot Copilot",  "hotshotcopilot",             Upg::Crew,              {Upg::Crew},              4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Jyn Erso",                     "Jyn Erso",         "jynerso",                    Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Cassian Andor",                "Cassian Andor",    "cassianandor",               Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Baze Malbus",                  "Baze Malbus",      "bazemalbus",                 Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Bistan",                       "Bistan",           "bistan",                     Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Bodhi Rook",                   "Bodhi Rook",       "bodhirook",                  Upg::Crew,              {Upg::Crew},              1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Inspiring Recruit",            "Insp Recruit",     "inspiringrecruit",           Upg::Crew,              {Upg::Crew},              1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Captain Rex",                  "Capt. Rex",        "captainrex",                 Upg::Crew,              {Upg::Crew},              2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Kylo Ren",                     "Kylo Ren",         "kyloren",                    Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "General Hux",                  "Gen. Hux",         "generalhux",                 Upg::Crew,              {Upg::Crew},              5, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Operations Specialist",        "Ops Specialist",   "operationsspecialist",       Upg::Crew,              {Upg::Crew},              3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Unkar Plutt",                  "Unkay Plutt",      "unkarplutt",                 Upg::Crew,              {Upg::Crew},              1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "BoShek",                       "BoShek",           "boshek",                     Upg::Crew,              {Upg::Crew},             99, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },

  { "Millennium Falcon",            "MF",               "millenniumfalcon",           Upg::Title,             {Upg::Title},             1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, aMFAL, ANone, UNone, UNone }, {} },
  { "Slave 1",                      "Slave 1",          "slave1",                     Upg::Title,             {Upg::Title},             0, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Moldy Crow",                   "Moldy Crow",       "moldycrow",                  Upg::Title,             {Upg::Title},             3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "ST-321",                       "ST-321",           "st321",                      Upg::Title,             {Upg::Title},             3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Royal Guard TIE",              "Royal Guard",      "royalguardtie",              Upg::Title,             {Upg::Title},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, uRGTI, UNone }, {} },
  { "A-Wing Test Pilot",            "Test Pilot",       "awingtestpilot",             Upg::Title,             {Upg::Title},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, uAWTP, UNone }, {} },
  { "B-Wing/E2",                    "E2",               "bwinge2",                    Upg::Title,             {Upg::Title},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, uBWE2, UNone }, {} },
  { "Outrider",                     "Outrider",         "outrider",                   Upg::Title,             {Upg::Title},             5, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Dauntless",                    "Dauntless",        "dauntless",                  Upg::Title,             {Upg::Title},             2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "BTL-A4 Y-Wing",                "BTL-A4",           "btla4ywing",                 Upg::Title,             {Upg::Title},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Andrasta",                     "Andrasta",         "andrasta",                   Upg::Title,             {Upg::Title},             0, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, uANDR, UNone }, {} },
  { "\"Heavy Scyk\" Interceptor",   "Heavy Scyk",       "heavyscykinterceptor",       Upg::Title,             {Upg::Title},             2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Virago",                       "Virago",           "virago",                     Upg::Title,             {Upg::Title},             1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, uVIRA, UNone }, {} },
  { "IG-2000",                      "IG-2000",          "ig2000",                     Upg::Title,             {Upg::Title},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "TIE/x1",                       "TIE/x1",           "tiex1",                      Upg::Title,             {Upg::Title},             0, false, false, { SNone, SNone, SNone, SNone, SNone, cTIX1, ANone, ANone, uTIX1, UNone }, {} },
  { "Hound's Tooth",                "Hounds Tooth",     "houndstooth",                Upg::Title,             {Upg::Title},             6, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Ghost",                        "Ghost",            "ghost",                      Upg::Title,             {Upg::Title},             0, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Phantom",                      "Phantom",          "phantom",                    Upg::Title,             {Upg::Title},             0, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "TIE/v1",                       "TIE/v1",           "tiev1",                      Upg::Title,             {Upg::Title},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Mist Hunter",                  "Mist Hunter",      "misthunter",                 Upg::Title,             {Upg::Title},             0, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, aMHUN, ANone, UNone, UNone }, {} },
  { "Punishing One",                "Punishing One",    "punishingone",               Upg::Title,             {Upg::Title},            12, true,  false, { SNone,  S(1), SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "TIE/x7",                       "TIE/x7",           "tiex7",                      Upg::Title,             {Upg::Title},            -2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, uTIX7 }, {} },
  { "TIE/D",                        "TIE/D",            "tied",                       Upg::Title,             {Upg::Title},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "TIE Shuttle",                  "TIE Shuttle",      "tieshuttle",                 Upg::Title,             {Upg::Title},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, uaTIS, urTIS }, {} },
  { "Alliance Overhaul",            "Alli Overhaul",    "allianceoverhaul",           Upg::Title,             {Upg::Title},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Special Ops Training",         "SpecOps Train",    "specialopstraining",         Upg::Title,             {Upg::Title},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Concord Dawn Protector",       "CD Protector",     "concorddawnprotector",       Upg::Title,             {Upg::Title},             1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Shadow Caster",                "Shadow Caster",    "shadowcaster",               Upg::Title,             {Upg::Title},             3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Black One",                    "Black One",        "blackone",                   Upg::Title,             {Upg::Title},             1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Millennium Falcon",            "MF (HOTR)",        "millenniumfalcon-swx57",     Upg::Title,             {Upg::Title},             1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Pivot Wing",                   "Pivot Wing",       "pivotwing",                  Upg::Title,             {Upg::Title},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Adaptive Ailerons",            "Adapt Ailerons",   "adaptiveailerons",           Upg::Title,             {Upg::Title},             0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Sabine's Masterpiece",         "Sabine's Mpiece",  "sabinesmasterpiece",         Upg::Title,             {Upg::Title},             1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, uSAMP, UNone }, {} },
  { "Kylo Ren's Shuttle",           "Kylo Ren's",       "kylorensshuttle",            Upg::Title,             {Upg::Title},             2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, uSAMP, UNone }, {} },

  { "Engine Upgrade",               "EU",               "engineupgrade",              Upg::Modification,      {Upg::Modification},      4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, aENUP, ANone, UNone, UNone }, {} },
  { "Shield Upgrade",               "SU",               "shieldupgrade",              Upg::Modification,      {Upg::Modification},      4, false, false, { SNone, SNone, SNone, SNone,  S(1), SNone, ANone, ANone, UNone, UNone }, {} },
  { "Stealth Device",               "Stealth Dev",      "stealthdevice",              Upg::Modification,      {Upg::Modification},      3, false, false, { SNone, SNone,  S(1), SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Anti-Pursuit Lasers",          "AntiPursuit L",    "antipursuitlasers",          Upg::Modification,      {Upg::Modification},      2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Hull Upgrade",                 "HU",               "hullupgrade",                Upg::Modification,      {Upg::Modification},      3, false, false, { SNone, SNone, SNone,  S(1), SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Targeting Computer",           "Targeting Comp",   "targetingcomputer",          Upg::Modification,      {Upg::Modification},      2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, aTCOM, ANone, UNone, UNone }, {} },
  { "Munitions Failsafe",           "Muni Failsafe",    "munitionsfailsafe",          Upg::Modification,      {Upg::Modification},      1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Advanced Cloaking Device",     "Adv Cloak Dev",    "advancedcloakingdevice",     Upg::Modification,      {Upg::Modification},      4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Stygium Particle Accelerator", "Styg Part Accl",   "stygiumparticleaccelerator", Upg::Modification,      {Upg::Modification},      2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Countermeasures",              "Countermeas",      "countermeasures",            Upg::Modification,      {Upg::Modification},      3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Experimental Interface",       "EI",               "experimentalinterface",      Upg::Modification,      {Upg::Modification},      3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Tactical Jammer",              "Tact Jammer",      "tacticaljammer",             Upg::Modification,      {Upg::Modification},      1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Autothrusters",                "Autothrusters",    "autothrusters",              Upg::Modification,      {Upg::Modification},      2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Ion Projector",                "Ion Projector",    "ionprojector",               Upg::Modification,      {Upg::Modification},      2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Maneuvering Fins",             "Maneuv Fins",      "maneuveringfins",            Upg::Modification,      {Upg::Modification},      1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Advanced SLAM",                "Adv SLAM",         "advancedslam",               Upg::Modification,      {Upg::Modification},      2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Twin Ion Engine Mk. 2",        "TIE Mk 2",         "twinionenginemk2",           Upg::Modification,      {Upg::Modification},      1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Integrated Astromech",         "Integrated Ast",   "integratedastromech",        Upg::Modification,      {Upg::Modification},      0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Guidance Chips",               "Guidance Chips",   "guidancechips",              Upg::Modification,      {Upg::Modification},      0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Long-Range Scanners",          "LR Scanners",      "longrangescanners",          Upg::Modification,      {Upg::Modification},      0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Vectored Thrusters",           "Vectored Thr",     "vectoredthrusters",          Upg::Modification,      {Upg::Modification},      2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, aVECT, ANone, UNone, UNone }, {} },
  { "Gyroscopic Targeting",         "Gyro Targeting",   "gyroscopictargeting",        Upg::Modification,      {Upg::Modification},      2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Smuggling Compartment",        "Smuggling Comp",   "smugglingcompartment",       Upg::Modification,      {Upg::Modification},      0, false, true,  { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, uSCOM, UNone }, {} },
  { "Lightweight Frame",            "LW Frame",         "lightweightframe",           Upg::Modification,      {Upg::Modification},      2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Captured TIE",                 "Captured TIE",     "capturedtie",                Upg::Modification,      {Upg::Modification},      1, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Spacetug Tractor Array",       "Spacetug Tractor", "spacetugtractorarray",       Upg::Modification,      {Upg::Modification},      2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },

  { "Heavy Laser Cannon",           "HLC",              "heavylasercannon",           Upg::Cannon,            {Upg::Cannon},            7, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Ion Cannon",                   "Ion Cannon",       "ioncannon",                  Upg::Cannon,            {Upg::Cannon},            3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Autoblaster",                  "Autobaster",       "autoblaster",                Upg::Cannon,            {Upg::Cannon},            5, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "\"Mangler\" Cannon",           "Mangler",          "manglercannon",              Upg::Cannon,            {Upg::Cannon},            4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Flechette Cannon",             "Flechette",        "flechettecannon",            Upg::Cannon,            {Upg::Cannon},            2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Tractor Beam",                 "Tractor Beam",     "tractorbeam",                Upg::Cannon,            {Upg::Cannon},            1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },

  { "Proximity Mines",              "Prox Mines",       "proximitymines",             Upg::Bomb,              {Upg::Bomb},              3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Seismic Charges",              "Seismic Chrgs",    "seismiccharges",             Upg::Bomb,              {Upg::Bomb},              2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Proton Bombs",                 "Proton Bombs",     "protonbombs",                Upg::Bomb,              {Upg::Bomb},              5, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Conner Net",                   "Connor Net",       "connernet",                  Upg::Bomb,              {Upg::Bomb},              4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Ion Bombs",                    "Ion Bombs",        "ionbombs",                   Upg::Bomb,              {Upg::Bomb},              2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Cluster Mines",                "Cluster Mines",    "clustermines",               Upg::Bomb,              {Upg::Bomb},              4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Thermal Detonators",           "Therm Det",        "thermaldetonators",          Upg::Bomb,              {Upg::Bomb},              3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },

  { "Advanced Sensors",             "Adv Sensors",      "advancedsensors",            Upg::System,            {Upg::System},            3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Sensor Jammer",                "Sensor Jammer",    "sensorjammer",               Upg::System,            {Upg::System},            4, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Fire-Control System",          "FCS",              "firecontrolsystem",          Upg::System,            {Upg::System},            2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Enhanced Scopes",              "Enh Scopes",       "enhancedscopes",             Upg::System,            {Upg::System},            1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Accuracy Corrector",           "Acc Correct",      "accuracycorrector",          Upg::System,            {Upg::System},            3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Adv. Targeting Computer",      "ATC",              "advtargetingcomputer",       Upg::System,            {Upg::System},            5, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Reinforced Deflectors",        "Reinforced Def",   "reinforceddeflectors",       Upg::System,            {Upg::System},            3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Electronic Baffle",            "Electronic Baf",   "electronicbaffle",           Upg::System,            {Upg::System},            1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Collision Detector",           "Collision Det",    "collisiondetector",          Upg::System,            {Upg::System},            0, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },

  { "\"Genius\"",                   "Genius",           "genius",                     Upg::SalvagedAstromech, {Upg::SalvagedAstromech}, 0, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R4 Agromech",                  "R4",               "r4agromech",                 Upg::SalvagedAstromech, {Upg::SalvagedAstromech}, 2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R4-B11",                       "R4-B11",           "r4b11",                      Upg::SalvagedAstromech, {Upg::SalvagedAstromech}, 3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Salvaged Astromech",           "Salvaged",         "salvagedastromech",          Upg::SalvagedAstromech, {Upg::SalvagedAstromech}, 2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Unhinged Astromech",           "Unhinged",         "unhingedastromech",          Upg::SalvagedAstromech, {Upg::SalvagedAstromech}, 1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "R5-P8",                        "R5-P8",            "r5p8",                       Upg::SalvagedAstromech, {Upg::SalvagedAstromech}, 3, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Overcocked R4",                "Overclkd R4",      "overclockedr4",              Upg::SalvagedAstromech, {Upg::SalvagedAstromech}, 1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },

  { "\"Hot Shot\" Blaster",         "Hot Shot",         "hotshotblaster",             Upg::Illicit,           {Upg::Illicit},           3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Inertial Dampeners",           "Inertial Damp",    "inertialdampeners",          Upg::Illicit,           {Upg::Illicit},           1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Dead Man's Switch",            "Dead Mans Sw",     "deadmansswitch",             Upg::Illicit,           {Upg::Illicit},           2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Feedback Array",               "Feedback Ar",      "feedbackarray",              Upg::Illicit,           {Upg::Illicit},           2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Glitterstim",                  "Glitterstim",      "glitterstim",                Upg::Illicit,           {Upg::Illicit},           2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Cloaking Device",              "Cloak Dev",        "cloakingdevice",             Upg::Illicit,           {Upg::Illicit},           2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Rigged Cargo Chute",           "Rigged Cargo",     "riggedcargochute",           Upg::Illicit,           {Upg::Illicit},           1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Black Market Slicer Tools",    "BMST",             "blackmarketslicertools",     Upg::Illicit,           {Upg::Illicit},           1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Burnout SLAM",                 "Burnout SLAM",     "burnoutslam",                Upg::Illicit,           {Upg::Illicit},           1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, aBOSL, ANone, UNone, UNone }, {} },
  { "EMP Device",                   "EMP Device",       "empdevice",                  Upg::Illicit,           {Upg::Illicit},           2, true,  false, { SNone, SNone, SNone, SNone, SNone, SNone, aBOSL, ANone, UNone, UNone }, {} },
  { "Scavenger Crane",              "Scavenger Crane",  "scavengercrane",             Upg::Illicit,           {Upg::Illicit},           2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, aBOSL, ANone, UNone, UNone }, {} },
  
  { "Weapons Guidance",             "Weap Guidance",    "weaponsguidance",            Upg::Tech,              {Upg::Tech},              2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Comm Relay",                   "Comm Relay",       "commrelay",                  Upg::Tech,              {Upg::Tech},              3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Sensor Cluster",               "Sensor Cluster",   "sensorcluster",              Upg::Tech,              {Upg::Tech},              2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Pattern Analyzer",             "Pattern Analuzer", "patternanalyzer",            Upg::Tech,              {Upg::Tech},              2, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Primed Thrusters",             "Primed Thristers", "primedthrusters",            Upg::Tech,              {Upg::Tech},              1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Targeting Synchronizer",       "Targeting Sync",   "targetingsynchronizer",      Upg::Tech,              {Upg::Tech},              3, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },
  { "Hyperwave Comm Scanner",       "HW Comm Scanner",  "hyperwavecommscanner",       Upg::Tech,              {Upg::Tech},              1, false, false, { SNone, SNone, SNone, SNone, SNone, SNone, ANone, ANone, UNone, UNone }, {} },

};
